### ISSUE TITLE
Audio distortion

### ISSUE THREAD

**Issue by danielnazareth-hotmart** [protyposis/ITEC-MediaPlayer#38] opened 2016-11-29 21:08 UTC
When the audio speed is changed, it is distorted, theres a way to change speed without distorting voices?

**Comment by protyposis** [comment] 2016-11-29 23:11
There's currently no way. It might be possible from API 23, older API versions do no offer any audio time stretching algorithm.

Duplicate of #24

**Closed as completed** 2018-03-15 19:59 UTC
