### ISSUE TITLE
IllegalStateException: onPrepared()

### ISSUE THREAD

**Issue by hfeky** [protyposis/ITEC-MediaPlayer#66] opened 2017-05-26 00:06 UTC
Whenever I try to play any music file in activity onCreate(), the app crashes onPrepared(). An IllegalStateException occurs. I saw the source code of this library, and it turned out that the EventHandler calls MEDIA_PREPARED before mCurrentState is equal to State.PREPARED. This issue does not occur in all devices, but it occurs around 30% of them, which is really a lot. What's the reason behind that? Is there anything wrong in my code or is it a bug?

Code:

        int backgroundMusic = 0;
        musicPlayer = new MediaPlayer();
        musicPlayer.setLooping(true);
        musicVolume = (float) (1 - (Math.log(100 - sharedPreferences.getInt("music_volume", 75)) / Math.log(100)));
        musicPlayer.setVolume(musicVolume);
        musicPlayer.setOnPreparedListener(new MediaPlayer.OnPreparedListener() {
            @Override
            public void onPrepared(MediaPlayer mp) {
                musicPlayer.start();
            }
        });

        musicSelection = sharedPreferences.getInt("music_selection", 0);

        switch (musicSelection) {
            case 0:
                backgroundMusic = R.raw.music1;
                break;
            case 1:
                backgroundMusic = R.raw.music2;
                break;
            case 2:
                backgroundMusic = R.raw.music3;
                break;
            case 3:
                backgroundMusic = R.raw.music4;
                break;
            case 4:
                backgroundMusic = R.raw.music5;
                break;
            case 5:
                backgroundMusic = 0;
                break;
        }

        Uri uri = null;
        if (backgroundMusic != 0) {
            uri = Uri.parse("android.resource://" + getPackageName() + "/" + backgroundMusic);
        } else {
            String uriString = sharedPreferences.getString("song_uri", null);
            if (uriString != null && !uriString.isEmpty()) uri = Uri.parse(uriString);
        }
        if (uri != null) {
            try {
                musicPlayer.reset();
                musicPlayer.setDataSource(new UriSource(this, uri));
                musicPlayer.prepareAsync();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

Crash Log:

```
                  java.lang.IllegalStateException
                      at net.protyposis.android.mediaplayer.MediaPlayer.start(MediaPlayer.java:527)
                      at com.example.app.MainActivity$2.onPrepared(MainActivity.java:237)
                      at net.protyposis.android.mediaplayer.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:1623)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by protyposis** [comment] 2017-05-26 08:24
Hi, how do you come to the conclusion that `MEDIA_PREPARED` is called before the state is set to `PREPARED`? Looking [here](https://github.com/protyposis/MediaPlayer-Extended/blob/569702d6c77c840af0514690ce8ac13140eaad6f/MediaPlayer/src/main/java/net/protyposis/android/mediaplayer/MediaPlayer.java#L1000), it's exactly the right order. Still, your exception obviously tells another story. What happens if you leave out the `reset()` call before `setDataSource(...)`?

**Comment by hfeky** [comment] 2017-05-26 18:37
Hi, the problem still occurs after removing `reset()`. I am also surprised like you that this exception occurs. It shouldn't happen. I know, but unfortunately, there is something wrong. I don't know what it is. It also doesn't occur on all devices as I said. So can it be that it failed to read the music file? All my music files are of the same file type (mp3) and they all have a bitrate of 128000 and sample-rate of 44100. 

The exception is produced on the Android Emulator (API 25) but does not occur on my own device (API 23). However, it occurs on some users' devices according to Google Play Console. So far, the impacted users are 388 with reports total of 717. There isn't really anything that determines which kind of devices this issue occurs on. It occurs on all android versions from low amount of RAM to high amount of RAM.

This is the complete log of anything regarding audio:

```
05-26 20:00:33.962 4281-4281/com.example.app D/MediaPlayer: {mime=audio/mpeg, channel-count=2, track-id=1, bitrate=128000, durationUs=90540408, encoder-delay=576, encoder-padding=1105, sample-rate=44100}
05-26 20:00:33.964 4281-4281/com.example.app D/MediaPlayer: {mime=audio/mpeg, channel-count=2, track-id=1, bitrate=128000, durationUs=90540408, encoder-delay=576, encoder-padding=1105, sample-rate=44100}
05-26 20:00:33.971 4281-4281/com.example.app D/MediaPlayer: selected audio track #0 {mime=audio/mpeg, channel-count=2, track-id=1, bitrate=128000, durationUs=90540408, encoder-delay=576, encoder-padding=1105, sample-rate=44100}
05-26 20:00:33.973 4281-4281/com.example.app D/MediaPlayer: PlaybackThread started
05-26 20:00:34.156 4281-4956/com.example.app D/AudioPlayback: init
05-26 20:00:34.169 4281-4956/com.example.app D/AudioTrack: Client defaulted notificationFrames to 2048 for frameCount 4096
05-26 20:00:34.215 4281-4956/com.example.app D/MediaCodecAudioDecoder: reinitCodec 156ms
05-26 20:00:34.267 4281-4956/com.example.app D/MediaCodecAudioDecoder: seeking to:                 0
05-26 20:00:34.267 4281-4956/com.example.app D/MediaCodecAudioDecoder: extractor current position: 0
05-26 20:00:34.269 4281-4956/com.example.app D/MediaCodecAudioDecoder: extractor new position:     26122
05-26 20:00:35.159 4281-4956/com.example.app D/MediaCodecAudioDecoder: output format has changed to {pcm-encoding=2, mime=audio/raw, channel-count=2, sample-rate=44100}
05-26 20:00:35.159 4281-4956/com.example.app D/AudioPlayback: init
05-26 20:00:35.178 4281-4956/com.example.app D/AudioTrack: Client defaulted notificationFrames to 2048 for frameCount 4096
05-26 20:00:35.380 4281-4956/com.example.app D/MediaCodecAudioDecoder: decoder released
05-26 20:00:35.421 4281-4956/com.example.app D/MediaPlayer: PlaybackThread destroyed
05-26 20:00:41.510 4281-4281/com.example.app D/MediaPlayer: {mime=audio/mpeg, channel-count=2, track-id=1, bitrate=128000, durationUs=90540408, encoder-delay=576, encoder-padding=1105, sample-rate=44100}
05-26 20:00:41.514 4281-4281/com.example.app D/MediaPlayer: {mime=audio/mpeg, channel-count=2, track-id=1, bitrate=128000, durationUs=90540408, encoder-delay=576, encoder-padding=1105, sample-rate=44100}
05-26 20:00:41.529 4281-4281/com.example.app D/MediaPlayer: selected audio track #0 {mime=audio/mpeg, channel-count=2, track-id=1, bitrate=128000, durationUs=90540408, encoder-delay=576, encoder-padding=1105, sample-rate=44100}
05-26 20:00:41.539 4281-4281/com.example.app D/MediaPlayer: PlaybackThread started
05-26 20:00:42.174 4281-4281/com.example.app D/MediaPlayer: onPrepared
05-26 20:00:42.177 4281-4281/com.example.app D/AndroidRuntime: Shutting down VM
                                                                              
                                                                              
                                                                              --------- beginning of crash
05-26 20:00:42.177 4281-4281/com.example.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.example.app, PID: 4281
                                                                              java.lang.IllegalStateException
                                                                                  at net.protyposis.android.mediaplayer.MediaPlayer.start(MediaPlayer.java:527)
                                                                                  at com.example.app.MainActivity$2.onPrepared(MainActivity.java:237)
                                                                                  at net.protyposis.android.mediaplayer.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:1623)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
05-26 20:00:42.308 4281-5080/com.example.app D/AudioPlayback: init
05-26 20:00:42.323 4281-5080/com.example.app D/AudioTrack: Client defaulted notificationFrames to 2048 for frameCount 4096
05-26 20:00:42.619 4281-5080/com.example.app D/MediaCodecAudioDecoder: reinitCodec 416ms
05-26 20:00:42.637 4281-5080/com.example.app D/MediaCodecAudioDecoder: seeking to:                 0
05-26 20:00:42.638 4281-5080/com.example.app D/MediaCodecAudioDecoder: extractor current position: 0
05-26 20:00:42.639 4281-5080/com.example.app D/MediaCodecAudioDecoder: extractor new position:     26122
05-26 20:00:43.008 4281-5080/com.example.app D/MediaCodecAudioDecoder: output format has changed to {pcm-encoding=2, mime=audio/raw, channel-count=2, sample-rate=44100}
05-26 20:00:43.008 4281-5080/com.example.app D/AudioPlayback: init
05-26 20:00:43.033 4281-5080/com.example.app D/AudioTrack: Client defaulted notificationFrames to 2048 for frameCount 4096
```

**Comment by hfeky** [comment] 2017-05-27 02:19
After some trial and error, I managed to fix the problem, although I don't why that affected it.

I had in `onDestroy()` `musicPlayer.release();`. When I removed that code, the app worked, and the music played perfectly. It turned out that the app called `musicPlayer.release();` while preparing the file. So I added a boolean in `onPrepared()` and called it `isPrepared` to know if the media player loaded the music or not, and then I added in `onDestroy()` this line:

`if (isPrepared) musicPlayer.release();`

You may ask why did the app even call `onDestroy()` on creating the activity. It was called because the orientation is changed in some circumstances on activity creation, thus it calls `onDestroy()` before recreating the activity, and it tried to release an already preparing media file.

Although I don't know why `release()` caused the problem, adding that boolean actually fixed the problem.

So far the problem didn't occur again. I will post updates if it still persists, but hopefully it won't.

**Comment by HusseinElFeky** [comment] 2017-06-13 12:37
Unfortunately, the issue still occurs but with less amount of reports. On my old version, I received 626 reports, while on my new version after adding what I posted above, I received 15 reports only. Although that is still a huge difference, it is still counted as an issue in my app that I need to fix.

Is there any solution?

**Comment by hfeky** [comment] 2017-06-13 12:37
Unfortunately, the issue still occurs but with less amount of reports. On my old version, I received 626 reports, while on my new version after adding what I posted above, I received 15 reports only. Although that is a huge difference, it is still counted as an issue in my app that I need to fix.

Is there any solution?

**Comment by protyposis** [comment] 2017-06-23 14:20
Hi! The stacktrace says that you are calling `start()` on an instance that is not prepared. Either it's not prepared because you didn't wait for `prepareAsync()` to finish, or you released it in between with `release()`. We can exclude the first option since you call `start()` from the `OnPreparedListener`, so as far as I can see, only the second option remains. 

Can you still reproduce the error? What if you don't call `release()` or `stop()` or `reset()` (which are actually all the same) at all, do you still get the error?

**Comment by hfeky** [comment] 2017-07-01 18:34
Yup, as you said, the second option was the cause. I removed `release()` from `onDestroy()`, and it never occurred again, but I can't leave it like that. I have to release the `MediaPlayer` `onDestroy()`. Sometimes `onDestroy()` is called before `MediaPlayer` gets prepared because I set device's orientation according to user's pre-defined option from the app's settings in `onCreate()` of the activity (and I `start()` the `MediaPlayer` in `onCreate()` as well), and you know, when the orientation is changed, the activity gets recreated. I can't use `onConfigChanges()` solution because my layout is different in landscape mode.

So far, I subclassed the `MediaPlayer` class and caught the `IllegalStateException` in `start()` method. It's not a clean solution I know, but at least better than a crash.

**Comment by hfeky** [comment] 2017-07-02 19:53
I think a good fix to this would be to remove `onPreparedListener()` by setting the listener to null whenever `release()` method is called. What do you think?

**Comment by protyposis** [comment] 2017-07-07 16:35
Yes that's a great fix, probably the best and cleanest solution! I guess the library should do this on its own, will look into that for the next version.

**Comment by hfeky** [comment] 2017-07-13 22:45
Alright, great! I'm looking forward to it.

**Comment by protyposis** [comment] 2017-08-17 18:11
The just released version `4.3.1-rc1` contains a fix for this issue. If you have a chance to test it, please let me know if it solves the issue. Thanks!

**Comment by protyposis** [comment] 2017-09-01 15:03
Final `4.3.1` is out, closing this now.

**Closed as completed by protyposis** 2017-09-01 15:03 UTC

**Comment by hfeky** [comment] 2017-10-07 12:08
Hello @protyposis. I know this is a late response. However, I am just writing this to confirm that it's working now. Thanks!

**Comment by protyposis** [comment] 2017-10-07 16:12
Great, thanks!
