### ISSUE TITLE
Mpeg-ts over http stream stops

### ISSUE THREAD

**Issue by incuboprist** [protyposis/ITEC-MediaPlayer#50] opened 2017-01-17 09:25 UTC
Mpeg-ts over http stream. It play, but after a few seconds stop. Any idea why and how to restart? OnError not fired.

Device One plus one android 6.0.1

@Override
protected void onCreate(Bundle savedInstanceState) {
	super.onCreate(savedInstanceState);
	setContentView(R.layout.activity_main);
	
	videoView = (VideoView) findViewById(R.id.video_view);
	videoView.setVideoSource(new UriSource(this, uri));
	videoView.setOnPreparedListener(this);
	videoView.setOnErrorListener(this);
}
@Override
public void onPrepared(MediaPlayer mp) {
	videoView.start();
}
@Override
public boolean onError(MediaPlayer mp, int what, int extra) {
	Log.e("MainActivity", "Video error");
	return true;
}

01-17 12:10:14.369 24790-24953/ru.ots_net.mediaplayer I/NuCachedSource2: Cache full, done prefetching for now
01-17 12:10:14.369 24790-24953/ru.ots_net.mediaplayer I/NuCachedSource2: restarting prefetcher, totalSize = 65536
01-17 12:10:14.371 24790-24953/ru.ots_net.mediaplayer I/NuCachedSource2: new range: offset= 20709376
01-17 12:10:14.470 24790-24953/ru.ots_net.mediaplayer D/MediaHTTPConnection: proxy null port 0
01-17 12:10:14.688 24790-24953/ru.ots_net.mediaplayer W/MediaHTTPConnection: readAt 20709376 / 32768 => java.net.ProtocolException
01-17 12:10:14.688 24790-24953/ru.ots_net.mediaplayer E/NuCachedSource2: source returned error -1010, 0 retries left
01-17 12:10:14.689 24790-25135/ru.ots_net.mediaplayer I/FFMPEG: [mpegts @ 0x9ee5b400] PES packet size mismatch
01-17 12:10:14.698 24790-25135/ru.ots_net.mediaplayer E/FFmpegExtractor: mFormatCtx->pb->error: -1010

**Comment by protyposis** [comment] 2017-01-17 18:30
The stream probably stops because the HTTP connection fails and there is an error in the TS stream (PES size mismatch). One is probably caused by the other. To restart the video, just `setVideoSource` again.

This is not an issue of MediaPlayer-Extended, but of the TS stream and/or the underlying Android system. I'm therefore closing this issue.

**Closed as completed by protyposis** 2017-01-17 18:30 UTC
