### ISSUE TITLE
MediaCodec.native_dequeueOutputBuffer(Native Method) - slow player release

### ISSUE THREAD

**Issue by xylik** [protyposis/ITEC-MediaPlayer#34] opened 2016-11-16 12:31 UTC
Hi, am facing native Android Exception while using MediaPlayer to play videos in list(recyler view). Currently in my application am using 2 players to play videos in list: 
- ExoPlayer to play from http stream 
- and MediaPlayer to play from sdcard(video-cache), why am using 2 players is because of very specific requirements that only ExoPlayer cant handle...

Am experiencing the isue with player version v4.0.0 and v4.1.2. Player is crashing with native Android exception which has something to do with slow releasing of player resources - i came to this conclusion by heavy debugging and looking into android logcat timestamps. 

SPECS:
Google Nexus 5
Marshmallow 6.0.1

TEMPORARY HACK:
When am delaying player release for at least 500 ms after play was initialized player is not crashing.

STACKTRACE:
11-16 13:07:19.533 1449-1449/D/playFromUri() -> playerMng: videoId:442
11-16 13:07:19.533 1449-1449/D/<=30 elapsedTime=8 ms
**11-16 13:07:19.561 1449-1449/D/playFromUriInternal() -> playerMng: videoId:442 uri: file:///some_local_mp4.mp4**
11-16 13:07:19.563 1449-1449/D/picked: mediaPlayer : videoId:442
11-16 13:07:19.568 1449-1449/D/playWithMediaPlayer() : videoId:442
11-16 13:07:19.650 1449-1449/D/showNextItem()
11-16 13:07:19.650 1449-1449/D/showNextItem() accepted: newNextIndx:2
11-16 13:07:19.780 1449-1449/D/showNextItem()
11-16 13:07:19.780 1449-1449/D/showNextItem() accepted: newNextIndx:2
**11-16 13:07:19.861 1449-1449/D/surfaceDestroyed() -> videoId:442**
11-16 13:07:19.861 1449-1449/D/release() -> mediaPlayer: videoId:442
11-16 13:07:19.861 1449-1449/D/drawingView -> null, videoId:442
11-16 13:07:19.861 1449-1449/D/mediaPlayer -> null, videoId:442
11-16 13:07:19.864 1449-1449/D/smoothScroll() + updateFocus() lastPos:1 newPos:2
11-16 13:07:19.865 1449-1449/D/release() -> playerMng : videoId:442
11-16 13:07:19.874 1449-1449/D/playFromUri() -> playerMng: videoId:440
11-16 13:07:19.874 1449-1449/D/<=30 elapsedTime=9 ms
**11-16 13:07:19.878 1449-5391/E/AndroidRuntime: FATAL EXCEPTION: Thread-1039
Process: io.honig.vequence, PID: 1449
java.lang.IllegalStateException
 at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379)
at net.protyposis.android.mediaplayer.MediaCodecDecoder.dequeueDecodedFrame(MediaCodecDecoder.java:292)
at net.protyposis.android.mediaplayer.Decoders.decodeFrame(Decoders.java:81)
at net.protyposis.android.mediaplayer.MediaPlayer.prepare(MediaPlayer.java:313)
at net.protyposis.android.mediaplayer.MediaPlayer$2.run(MediaPlayer.java:347)
at java.lang.Thread.run(Thread.java:818)**

_What is important to notice is those 2 events:_
**1)** timestamp when player was asked to play video
`11-16 13:07:19.561 1449-1449/D/playFromUriInternal() -> playerMng: videoId:442 uri: file:///some_local_mp4.mp4`
**2)** timestamp when player was released due to surface(TextureView) being destroyed
`11-16 13:07:19.861 1449-1449/D/surfaceDestroyed() -> videoId:442`

player-preparing_or_playing-duration_before_release = 19.861 - 19.561 = 300ms

**Comment by protyposis** [comment] 2016-11-16 18:30
Hi, thanks for the report. The problem was that you destroy your surface while the player is preparing. The exception is now caught and that should fix the problem.

**Comment by xylik** [comment] 2016-11-16 22:39
Thx for such a quick fix I was becoming desparate to make it all work :). I manage to reproduce one more native error. Error occurred when i pressed home button while player was playing:

11-16 23:22:22.871 28070-28070/io.fer.player E/AndroidRuntime: FATAL EXCEPTION: main
Process: io.fer.player, PID: 28070
java.lang.RuntimeException: Unable to pause activity {io.fer.player/io.fer.player.presentation.view.FeedActivity}: 
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.sendEmptyMessage(int)' on a null object reference
  at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3381)
  at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3340)
  at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3315)
  at android.app.ActivityThread.-wrap13(ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5417)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.sendEmptyMessage(int)' on a null object reference
   at net.protyposis.android.mediaplayer.MediaPlayer$PlaybackThread.release(MediaPlayer.java:739)
   at net.protyposis.android.mediaplayer.MediaPlayer$PlaybackThread.access$600(MediaPlayer.java:675)
   at net.protyposis.android.mediaplayer.MediaPlayer.stop(MediaPlayer.java:522)
   at net.protyposis.android.mediaplayer.MediaPlayer.release(MediaPlayer.java:529)
   at io.fer.player.data.player.MediaPlayerImp.release(MediaPlayerImp.java:332)
   at io.fer.player.data.player.VideoPlayManager.releasePlayer(VideoPlayManager.java:174)
   at io.fer.player.presentation.view.viewholder.MomentViewHolder.stopVideo(MomentViewHolder.java:524)
   at io.fer.player.presentation.presenter.MomentPresenterImpl.onPause(MomentPresenterImpl.java:113)
   at io.fer.player.presentation.view.adapter.MomentsAdapter.notifyActivityPaused(MomentsAdapter.java:71)
   at io.fer.player.presentation.view.custom.MomentsView$1.onActivityPaused(MomentsView.java:104)
   at io.fer.player.presentation.App$1.onActivityPaused(App.java:232)
   at android.app.Application.dispatchActivityPaused(Application.java:223)
   at android.app.Activity.onPause(Activity.java:1475)
   at android.support.v4.app.FragmentActivity.onPause(FragmentActivity.java:437)
   at io.fer.player.presentation.view.FeedActivity.onPause(FeedActivity.java:100)
   at android.app.Activity.performPause(Activity.java:6363)
   at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1311)
   at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3367)
   at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3340) 
   at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3315) 
   at android.app.ActivityThread.-wrap13(ActivityThread.java) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355) 
   at android.os.Handler.dispatchMessage(Handler.java:102) 
   at android.os.Looper.loop(Looper.java:148) 
   at android.app.ActivityThread.main(ActivityThread.java:5417) 
   at java.lang.reflect.Method.invoke(Native Method) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by protyposis** [comment] 2016-11-16 23:17
Are you calling release() twice on the same MediaPlayer? How can I reproduce this?

**Comment by xylik** [comment] 2016-11-16 23:50
Probably not but tomorrow I'll investigate it in more detail and give you feedback.

**Comment by xylik** [comment] 2016-11-17 11:58
I just checked the logs and player was probably not prepared when activity onPause happened due to transition to new activity. OnPause(followed by player release) happened 306ms after player prepare/play was called so that looks to me similar to the issue with surface destroy while player is preparing.

**Comment by protyposis** [comment] 2016-11-17 13:23
Thanks, I think I know what the problem is... should be fixed in a few days.

**Comment by protyposis** [comment] 2016-11-18 18:28
Fixed!

**Closed as completed** 2016-11-18 18:28 UTC
