### ISSUE TITLE
Bad audio quality when played in slow motion.

### ISSUE THREAD

**Issue by krishnadrivemail** [protyposis/ITEC-MediaPlayer#58] opened 2017-03-15 09:55 UTC
When I play video at normal speed ( i.e playback rate =1 ) the audio quality seems to be normal but when I change the playback rate to 0.5 or 0.75 the audio quality becomes bad.

**Comment by protyposis** [comment] 2017-03-15 15:58
Duplicate of #24, #38.

**Closed as completed by protyposis** 2017-03-15 15:58 UTC
