### ISSUE TITLE
Video rotate

### ISSUE THREAD

**Issue by 835127729** [protyposis/ITEC-MediaPlayer#49] opened 2017-01-13 06:41 UTC
I use my GN9005 to record a video, and then use mediaplayer-demo to play it.
I found the video been rotated,because I recorded the video vertically,but it shows horizontally.

Then I use annother phone to play this video, it shows normal(vertically).This stituation happens in some kinds of phone.

My English is poor so I make a photo to show it.
In GN9005:
![9f4d7ff062700a70bea0cf0517e16152 png](https://cloud.githubusercontent.com/assets/5118609/21919020/2f3cd1f0-d992-11e6-9533-546d6a0e1fb8.jpeg)

This is the video i use:

[video.zip](https://github.com/protyposis/MediaPlayer-Extended/files/703660/video.zip)

Hope for your help.

**Comment by protyposis** [comment] 2017-01-17 18:15
Duplicate of #6. Rotation works from API 21 (Android 5.0), there is no nice solution for older Android versions.

**Closed as completed by protyposis** 2017-01-17 18:15 UTC
