### ISSUE TITLE
Frozen video after codec reinitialization

### ISSUE THREAD

**Issue by oseparovic** [protyposis/ITEC-MediaPlayer#67] opened 2017-05-29 21:05 UTC
Hi there,

We're using v 4.3.0 of your lib in a Dash streaming application. I know you mentioned it's experimental but to be honest it's working quite well. On only one of our test devices (LG Lucid 2) we're having a strange issue where the logcat is flooded with the following messages:

`V/AudioTrack: Underrun user: 0, server: 0, flags 0013`

This messages repeats about 100 times a second. The streaming video still plays but it suddenly freezes 10-15 seconds after loading and completely locks our application and heavily hampers device performance; pressing back takes a few seconds and is unable to finish the activity (freezes on black screen with logcat still flooding these messages inidicating video is probably still playing in some way). 

I've tried looking through the logcat for error messages and the like and have breakpointed inside the onErrorListener but haven't found any clues as to what would be happening.

So two questions:

1. How would I go about debugging why this freeze is happening?
2. What does this logcat message indicate? Is it failing to load/play the audio track. Is this causing the video freeze or is it unrelated?

Thank you

**Comment by protyposis** [comment] 2017-06-23 14:24
Hi!

The log message seems specific to LG's Android implementation, so I can't help you with that. Does the issue only happen with DASH streaming, or when you stream a progressive file too?

I'd first look at memory consumption and see if it looks odd. All freezed I ever ran into were related to memory leaks where it would fill up until the system crashed.

**Comment by oseparovic** [comment] 2017-06-24 00:29
Hi there,

What do you mean by a progressive file?

I've tested a few things and would like to know what you think. MPD doesn't crash the app but makes it unresponsive without using up all the resources somehow. WEBM hard crashes the app at roughly the same point the MPD would start slowing down (a few seconds in).

## MPD test
First I ran the app with a test MPD stream and watched the memory usage ("http://www-itec.uni-klu.ac.at/dash/js/content/bunny_ibmff_240.mpd"). I've marked relevant points in the log

### Profiling
* GREEN - activity has opened and the stream has started loading
* YELLOW - stream has finished loading and starting playing 
* RED - stream freezes and application starts slowing down and becomes unresponsive

**profile image** - [http://i.imgur.com/d5qgzHB.png](http://i.imgur.com/d5qgzHB.png)

## WEBM test

I tried a webm (http://www-itec.uni-klu.ac.at/dash/js/content/bunny_4000.webm). After a few seconds of running I get the following crash:

```
E/AndroidRuntime: FATAL EXCEPTION: MediaPlayer#PlaybackThread
java.lang.IllegalArgumentException
   at android.media.MediaExtractor.readSampleData(Native Method)
   at net.protyposis.android.mediaplayer.MediaExtractor.readSampleData(MediaExtractor.java:258)
   at net.protyposis.android.mediaplayer.MediaCodecDecoder.queueSampleToCodec(MediaCodecDecoder.java:271)
   at net.protyposis.android.mediaplayer.Decoders.decodeFrame(Decoders.java:91)
   at net.protyposis.android.mediaplayer.MediaPlayer$PlaybackThread.loopInternal(MediaPlayer.java:1100)
   at net.protyposis.android.mediaplayer.MediaPlayer$PlaybackThread.handleMessage(MediaPlayer.java:963)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:137)
   at android.os.HandlerThread.run(HandlerThread.java:60)
```

After this I can no longer load a stream at all without instantly crashing the app when the VideoViewActivity is opened. To fix this I have to kill the app several times or actually restart the device. The logcat shows one of these two messages:

```
E/AndroidRuntime: FATAL EXCEPTION: Thread-475
java.lang.IllegalStateException
   at net.protyposis.android.mediaplayer.MediaPlayer.prepareAsync(MediaPlayer.java:466)
   at net.protyposis.android.mediaplayer.VideoView$2.run(VideoView.java:210)
   at java.lang.Thread.run(Thread.java:856)
```

OR 

```
E/AndroidRuntime: FATAL EXCEPTION: MediaPlayer#PlaybackThread
java.lang.NullPointerException
   at net.protyposis.android.mediaplayer.MediaPlayer.prepareInternal(MediaPlayer.java:432)
   at net.protyposis.android.mediaplayer.MediaPlayer.access$800(MediaPlayer.java:37)
   at net.protyposis.android.mediaplayer.MediaPlayer$PlaybackThread.prepareInternal(MediaPlayer.java:999)
   at net.protyposis.android.mediaplayer.MediaPlayer$PlaybackThread.handleMessage(MediaPlayer.java:951)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:137)
   at android.os.HandlerThread.run(HandlerThread.java:60)
```

### Profiling
* GREEN - activity has opened and the stream has started loading
* YELLOW - stream has finished loading and starting playing 
* RED - app crashes

**profile image** - [http://i.imgur.com/LYxlaeA.png](http://i.imgur.com/LYxlaeA.png)

**Comment by protyposis** [comment] 2017-06-26 21:02
Memory consumption looks great, so it's not a memory leak. For some reason the video decoder on your phone is crashing, which leads to the exceptions and behavior as described. I can't say what the reason is, only that I haven't heard of similar problems on other phones so my wild guess is that the video decoder implementation on this phone is flawed, and there's probably nothing I can do about that. Without being able to reproduce (the linked videos work on all my test devices), I'm afraid there is nothing else I can do about it.

Btw. with progressive file I mean a simgle video file (e.g. mp4, webm) that contains a single stream in a single quality (in contrast to DASH with multiple streams and qualities).

**Comment by oseparovic** [comment] 2017-06-28 18:59
Ok no problem, thanks for the help. I haven't reproduced on any other device (Galaxy S3, Blu X2, One Plus 3) nor have I heard from any users about it yet.

I'll close this for the time being and let you know if I see it on any other devices.

I did want to double check one thing: from my testing the network consistently drops off well before the freeze/crash happens. Is it possible that there's a bug with the networking in the lib? This phone is old and connection might not always be stable. Could there be issues around network timeouts/failures/retries?

**Comment by protyposis** [comment] 2017-06-28 19:21
That was my first thought when I read the underrun log message. It's strange though that you get the same behavior for DASH and webm streams, because the webm stream is downloaded by Android's MediaExtractor while DASH downloads are carried out through the OkHttp library. There's still the possibility that the problem lies somewhere deep in the system on a layer that is used by both download methods, but that is going to be really hard to debug, and there's again nothing we can do about it.

If it ever happens on other devices, please let me know. Thanks!

**Comment by oseparovic** [comment] 2017-08-04 18:27
Hello again,

I've seen this issue on another device. The `V/AudioTrack: Underrun user: 0, server: 0, flags 0013` log entry seems like it was LG specific and didn't actually cause or indicate the freezing issue.

The device I've reproduced it on is a Samsung Galaxy S3 (SGH-I747) running 4.2.2 (CM 10.1.3-d2att).

Also important to note that the video stopping **does not** freeze the app. I thought it did before because pressing back locked the app but the reason for that was that pressing back triggers `onPause()` which in turn calls:

```
if (mVideoView.isPlaying()) {
    mVideoView.stopPlayback();
    mVideoView.setVideoSource(null);
}
```

Here is where the real app freeze happens. For some reason doing this when the media player gets into this stopped state is what causes the app to freeze. If I comment out this block of code I can back out of the activity just fine.

Maybe adding some safety code to prevent the app freeze would be a better place to start and might lead to the source of the media player playback stopping?

Let me know if I can help you test anything.

**Comment by oseparovic** [comment] 2017-08-04 19:46
I happen to have two Samsung Galaxy S3 test devices. The other one seems to completely unaffected by this. A breakdown of devices tested on and their results:

**Works fine:**
* Samsung Galaxy S3 (SGH-I747) 
4.4.4 (cm_d2lte-userdebug 4.4.4 KTU84Q bdfbe2c9c2 test-keys)
* Blu Energy X2
5.1 (BLU_E050U_V11_GENERIC)
* OnePlus 3 (ONEPLUS A3000)
7.1.1 (ONEPLUS A3000_16_170411)

**Exhibits video freeze:**
* Samsung Galaxy S3 (SGH-I747)
4.2.2 (CM 10.1.3-d2att)
* Lucid 2 (VS870 4G)
4.1.2 (VS87011A)

**Video never starts playing (probably too old; too little memory)**
* HTC Desire A8181
4.1.2 (10.0.0-vjendra)

So far what I'm seeing is that perhaps there's a bug in the lib for devices running sdk 18 or less. Hope that helps.

**Comment by protyposis** [comment] 2017-08-06 19:31
Do I understand it correctly that the freeze also happens in the demo app? Can you please tell me exact steps to reproduce the problem? I've got 2 Samsung Galaxy S2 with Android 4.1.2 and they seem to be unaffected, but maybe I do not reproduce it correctly.

**Comment by oseparovic** [comment] 2017-08-08 05:14
I just tested the demo app. Exact same thing happens (my own VideoViewActivity is built off of yours).

## Tested on:
Samsung Galaxy S3 (SGH-I747)
4.2.2 (CM 10.1.3-d2att)

## Steps to reproduce

1. Start demo app
2. Click "Paste or type URL"
3. Paste "http://dj9wk94416cg5.cloudfront.net/sintel2/sintel.mpd"
4. Press OK
5. After finishes loading press "VideoView"
6. Once the VideoView finishes load click the screen once to bring up the overlay and press play
7. **WARNING** be ready to bring up the process list and swipe away the app. The video will now freeze in about 15-30s. **DO NOT PRESS BACK. IMMEDIATELY KILL THE APP**. Results after this point vary. If you let the video keep playing the sound will eventually stop and then the app will eventually freeze completely. On this test phone this leads to a kernel panic a few seconds later. 

## Logs

These are the last few seconds of logcat before the video freezes. As far as I can tell there's nothing out of the ordinary but there's a lot to go through
[output.txt](https://github.com/protyposis/MediaPlayer-Extended/files/1206958/output.txt)

**Comment by protyposis** [comment] 2017-08-08 20:11
Thanks for the detailed description, I still do not completely understand though.

> be ready to bring up the process list and swipe away the app. The video will now freeze in about 15-30s.

With process list, do you mean the list of running apps that opens when pressing the home button for a few seconds? The VideoView goes into a paused state as soon as the app goes into the background (which happens when opening this app switcher), and when I swipe it away, it's immediately killed and the video cannot continue running for 15-30s. So I guess you must be meaning something different, or is the app switcher in CyanogenMod totally different and does not put activities into the paused state?

**Comment by oseparovic** [comment] 2017-08-08 20:19
Yes by process list I meant list of running apps. The app switcher in cyanogenmod functions the same way. Don't kill the app until you reproduce the video freeze after 15-30 seconds. I added the app kill step because if I didn't kill the process after the video froze on my device it would completely lock the device cause a kernel panic (reboot) a few seconds later.

**Comment by protyposis** [comment] 2017-08-08 20:49
I just tried to reproduce on a Galaxy S3 with Android 4.3 and it is working normally. I'd probably have to get an S3 and flash it to that exact CM version you experience the issue on. Even then, it would be a "normal" S3 (i9300) as it's probably next to impossible to get my hands on the special AT&T version (d2att) here in Europe, and the chance remains that the issue only happens on the AT&T version. Same goes for the LG Lucid 2 which was never sold in Europe. So this would require considerable effort.

What percentage of your users is affected by this issue? I guess it's very important to get this fixed, else you wouldn't put that much effort into this issue? I'm afraid I won't be able to help here unless we find an affected mainstream device that I can get my hands on or somebody else drops by who is able to debug the issue.

**Comment by oseparovic** [comment] 2017-08-08 21:00
From what I can see I don't think the specific device matters. If the same device can both reproduce the error and work normally depending on the installed ROM I'm more likely to believe it's some kind of OS issue.

I'm sure your time is limited and this is currently only for an Alpha concept of a streaming app. Also it's impossible to tell how many users are currently affected because the freeze doesn't hit any of the callbacks like onError and instead causes an ANR or fully reboots the device neither of which are being logged in my developer console even when I reproduce them.

My guess is that if you wanted to reproduce the error it would be as simple as installing a similar ROM on your test device. For example if you can find and install CM 10.1.3 for your S2 I bet that would reproduce the error.

My main concern & why I'm putting so much effort into this, is that half of my current test devices are affected. It's important to me because this lib is awesome and I am fully reliant on it as ExoPlayer has very rigorous MPD parsing constraints and Steam (which is what I'm making the app for) does not perfectly respect MPD markup and I'm not interested in completely rewriting the parsing engine.

**Comment by protyposis** [comment] 2017-08-09 07:36
I was going to try that, CM on S2. Let's see how it turns out.

**Comment by protyposis** [comment] 2017-08-09 21:12
Didn't try to debug yet, but just wanted to let you know that I can reproduce it on an S2 with CM 10.1.3 :)

**Comment by oseparovic** [comment] 2017-08-09 21:14
That's great news! Thanks for all the help so far :)

**Comment by protyposis** [comment] 2017-08-16 18:34
I have identified and fixed the frozen video issue with DASH playback. This happened when the representation switched and the codec was recreated. Some platforms do not allow reuse of a codec instance, instead a new one must be created. Fix will be released in the next few days.

You said you also experience this issue with progressive streams. That is probably a different issue that needs to be addressed separately.

**Comment by oseparovic** [comment] 2017-08-16 18:44
woahhh this is amazing. Great find! I don't know enough about the underlying issue to say for sure, but the symptoms in the progressive video were very similar to those I listed above for the sample files. Here's to hoping they're related issues

**Comment by protyposis** [comment] 2017-08-17 18:10
I just published `4.3.1-rc1` with the DASH freeze fix. Please give it a try and see if it work for you. 

I could not reproduce the issue with progressive streams. Playback performance of webm content is very poor on my Galaxy S2 test devices, but none crashes. There are no video frames of webm/vp8/vp9 rendered in CM 10.1.2 (`runFimc fail`), but that seems to be a [bug in CM's decoder](https://forum.xda-developers.com/galaxy-s2/development-derivatives/rom-cyanogenmod-12-t2955551/page547) that affects other video players as well.

**Comment by oseparovic** [comment] 2017-08-17 18:38
Jitpack is failing to build the release candidate: https://jitpack.io/#protyposis/MediaPlayer-Extended

Also the video performance is bad on my LG Lucid 2 as well. They're just low memory devices, it's probably fine.

**Comment by protyposis** [comment] 2017-08-17 19:29
I don't support Jitpack (#2), the official releases are available in Android's default repository [JCenter](https://bintray.com/bintray/jcenter).

**Comment by oseparovic** [comment] 2017-08-17 20:20
It is on JCenter (https://bintray.com/protyposis/maven/MediaPlayer-Extended/4.3.1-rc1) and I've added it via

    compile 'net.protyposis.android.mediaplayer:mediaplayer:4.3.1-rc1'
    compile 'net.protyposis.android.mediaplayer:mediaplayer-dash:4.3.0'

but I'm not able to gradle sync

    Error:(33, 13) Failed to resolve: net.protyposis.android.mediaplayer:mediaplayer:4.3.1-rc1

**Comment by protyposis** [comment] 2017-08-17 20:34
It disappeared from JCenter for some reason. Working on adding it back.

**Comment by protyposis** [comment] 2017-08-18 15:33
Files are back online :)

**Comment by oseparovic** [comment] 2017-08-18 17:38
Awesome, got it. Looks like the issue is fixed. Tried on both devices that weren't working before:

* Samsung Galaxy S3 (SGH-I747)
4.2.2 (CM 10.1.3-d2att)
* Lucid 2 (VS870 4G)
4.1.2 (VS87011A)

No crashes, recovers nicely from bad network. No hanging or ANRs. Great work!

**Comment by protyposis** [comment] 2017-08-19 14:37
Great to hear, thanks!

**Closed as completed by protyposis** 2017-08-19 14:37 UTC
