### ISSUE TITLE
Fast switching video source issue

### ISSUE THREAD

**Issue by vishalkumarsinghvi** [protyposis/ITEC-MediaPlayer#61] opened 2017-04-10 07:12 UTC
same as issue 55 problem

**Comment by protyposis** [comment] 2017-04-10 07:43
Duplicate of #55.

**Closed as completed by protyposis** 2017-04-10 07:43 UTC

**Comment by vishalkumarsinghvi** [comment] 2017-04-10 07:54
it's not working please reopen issue

**Comment by vishalkumarsinghvi** [comment] 2017-04-11 06:54
Exception java.lang.IllegalStateException:
net.protyposis.android.mediaplayer.MediaPlayer.prepareAsync (MediaPlayer.java:466)
net.protyposis.android.mediaplayer.VideoView$2.run (VideoView.java:210)
java.lang.Thread.run (Thread.java:818)
