### ISSUE TITLE
Support MOV file

### ISSUE THREAD

**Issue by mavencode01** [protyposis/ITEC-MediaPlayer#7] opened 2015-07-20 00:50 UTC
This library does not support .mov format...demo app crashes each time I tried to load it.

Any idea of how to support .mov format ?

**Comment by protyposis** [comment] 2015-07-20 08:51
Hi, the Apple QuickTime container format (mov) is not supported by the Android system and can therefore not be played back by any video player using the system decoder. 

For this library to support mov, a custom MediaExtractor would have to be written. As a simple alternative, it might be also possible to convert the mov container to the supported and very similar mp4 container on the fly by using the isoparser library that is also used for DASH-support.

**Comment by mavencode01** [comment] 2015-07-23 13:22
@protyposis thanks! 
I got it working using this library https://github.com/Bilibili/ijkplayer

**Comment by protyposis** [comment] 2016-06-01 11:08
Closing this issue since this is not directly a problem of this library.

**Closed as completed by protyposis** 2016-06-01 11:08 UTC

**Comment by vxhviet** [comment] 2016-10-11 09:15
Dear @protyposis,

I have posted a [ticket ](https://github.com/google/ExoPlayer/issues/1901)on ExoPlayer's page for my particular problem. The quick summary is for my particular application, I need to work directly with the `MediaCodec` in order to implement video scrubbing feature. I've got all that working based on sample code from Grafika's [MoviePlayer](https://github.com/google/grafika/blob/master/src/com/android/grafika/MoviePlayer.java). The problem is as you could have guessed, `MediaExtractor` doesn't play nicely with `mp4` and `mov` created in `iOS`. 

After a quick skimming through your `MediaExtractor`, I can see that it's only built upon the stock `MediaExtractor`. I would like to ask is there anyway to custom the `MediaExtractor` so that it can understand iOS's files? Of course I've tried to re use `ExoPlayer`'s extractor but it's really becoming a little bit too complex.

Another question, as you have said, another simpler approach is using `isoparser` (I would assume it is [this one](https://github.com/sannies/mp4parser)) to convert the container into something stock `MediaExtractor` can understand. I'm not too familiar with `isoparser` so I would like to ask about its performance. As there is no actual transcoding being involved in the raw video data, I would assume it is pretty quick?

**Comment by protyposis** [comment] 2016-10-11 09:51
Hi, I don't think there is a way to customize the stock MediaExtractor. The two solutions I can think of are writing a custom MediaExtractor for those iOS files from scratch (like ExoPlayer), or repacking the iOS files into an Android-compatible MOV/MP4 container with isoparser (the one you linked). The first and most important step would be to analyze those files and find out what exactly the difference in those unsupported iOS videos is (maybe it's just a minor difference that can be solved easily).

In the DASH module of MediaPlayer-Extended I'm already doing something similar, namely repacking fragmented MP4 files into "normal" MP4 files with isoparser, because MediaExtractor does not support the fragmented format. It's in `DashMediaExtractor#handleSegment`.

What I remember from looking into isoparser's code, it isn't exactly written for high performance use cases, but as you say there is no transcoding involved so chances are this would be fairly quick.
